### ISSUE TITLE
Null Safety issues

### ISSUE THREAD

**Issue by oakstair** [gagoman/bitcount#1]
I am fixing null safety issues in a project and gets this.

```
Unable to spawn isolate: Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:bitcount
```

I guess this is due to the fact that this repo isn't upgraded to null safety.

is there any easy way around this for me?

**Comment by akhomchenko** [comment]
Thank you for letting me know. Released `0.2.0` with null safety support in d1508b8.
